### ISSUE TITLE
Create parserules for webshops in doc/webshop_ranking.csv

### ISSUE THREAD

**Issue by latinvm** [ServerDotBiz/ShopParser#1]
The file config.inc.php contains 4 sets of parse rules for 4 specific webshops, an example of a rule looks like this: 

```
'bartsmit.com' => array(
    'image' => array(
        'rule' => '#productMainImage',
        'attribute' => 'src'
    ),
    'title' => array(
        'rule' => 'div#productdetail div div#title h1',
        'attribute' => 'plaintext'
    ),
    'price' => array(
        'rule' => 'div#productdetail div meta[itemprop=price]',
        'attribute' => 'content',
        'filter' => '/([0-9]*)\.([0-9]*)/'
    ),
),
```

Basically a set of metadata consists of "title" (product name), "price" and "image". All this data is screenscraped from the webshop's product page using the "rule", "attribute" and optionally a regular expression filter.

The file doc/webshop_ranking.csv contains a list of all webshops we would like to support, in order of popularity and a column to indicate if we have added rules for that particular shop.

Basically all the different webshops need to be visited in order of popularity, using something like Firebug or another developer tool the the unique path to each piece of metadata needs to be identified and added to the rules.

To parse the domtree we use the "simple html dom" package, documentation can be found here: http://simplehtmldom.sourceforge.net

If you run the file index.php you should see something like this:

```
array(4) {
    ["shop"]=>
    string(12) "bartsmit.com"
    ["image"]=>
    string(53) "http://static.bartsmit.com/BLKCAS/380x380/1000570.jpg"
    ["title"]=>
    string(34) "LEGO Duplo basisstenen deluxe 6176"
    ["price"]=>
    string(5) "17,99"
}
```

Improvements to the parseSiteClass.php are welcome, to run this code you will need to have cURL installed on your development machine.

**Comment by ServerDotBiz** [comment]
Just a small not, to run this code you will need to have cURL installed on your development machine.

**Comment by latinvm** [comment]
I will update shops that don't have a valid URL, please skip them for now.

**Comment by icarius06** [comment]
Hey ,I can work on this task. Just to make sure that i have understood your requirements for this task,
You would like the config.inc.php class to be populated with a set of rules for all the urls listed on the excel sheet?

**Comment by latinvm** [comment]
Hi, good to hear that. Looking forward to working with you. That is correct, at the end the config file should be much bigger and there should be a nice list of test url's in that array in index.php :) 

All those url's are in order of importance in the excel sheet, the top ones are the ones that drive the most traffic.

**Comment by icarius06** [comment]
Hi sorry its taken a while to work on this. How do i submit this task? I have the rules and their respective test urls.

**Comment by latinvm** [comment]
Hi, I guess you should create a pull request with the changes so I can test them and close this issue. Perhaps Bart can confirm this?

**Comment by latinvm** [comment]
@icarius06: for some reason my CLI window keeps crashing right after the test for "gestrikt.nl". I think 1024M memory should be enough right? Perhaps there is a memory leak in my wrapper class or in simpledom? Did you experience any crashes?

**Comment by icarius06** [comment]
Hi ,I didn't encounter this personally. Are you still getting this?

**Comment by latinvm** [comment]
Yep, the CLI still crashes. Which version of PHP are you running?

**Comment by icarius06** [comment]
I'm running  5.5.9 on ubuntu.. Have you tried to increase the memory limit
for your php? Or commenting out the particular record where it fails?

**Comment by icarius06** [comment]
Im attaching my curl.log file so that you could compare with yours for
clues as to what might be causing the issue

**Comment by latinvm** [comment]
I am still running 5.3.10 on my windwos dev laptop, I increased memory from 1024 to 2048Mb (which should be more than enough) but it still crashed at the same point. I'll investigate further and try this on a VM that runs linux.

**Comment by latinvm** [comment]
The culprit seems to be "http://www.cameranu.nl/nl/p458254/nikon-d3200-dslr-zwart-18-55mm-vr-ii", as soon as I uncomment this URL everything works. If I leave this shop in, the CLI crashes a couple of URLs later. Quite strange.

**Comment by icarius06** [comment]
Thats strange indeed..perhaps you could try with a different test url for
that shop. Perhaps that might narrow down the issue.

**Comment by latinvm** [comment]
It's not a big deal, I'll continue to test some more... thanks for all your work!
